version: "3.4"

services:
  bot:
    container_name: dappnode-announcements-bot
    image: ghcr.io/dappnode/dappnode-announcements-bot:latest
    build:
      context: "./build"
    environment:
      GO_ENV: "production"
